---
version: 2.1

defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
  docker:
    - image: greenpeaceinternational/circleci-base:latest
  working_directory: /home/circleci/app

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build-push-tag:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker-login.sh
      - run: make build-tag push-tag
  build-push-branch:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker-login.sh
      - run: make build-branch push-branch

  send-jokes:
    docker:
      - image: greenpeaceinternational/planet4-dadjokes-to-chat:master
    working_directory: /app
    steps:
      - run:
          name: Get the joke
          command: |
            joke="$(./bin/joke.sh)"
            echo "export JOKE_MSG='${joke}'" >> $BASH_ENV
            echo "$joke"
      - slack/notify:
          channel: C014UMRC4AJ
          color: '#78c043'
          message: "${JOKE_MSG}"
          include_job_number_field: false
          include_project_field: false
          include_visit_job_action: false

workflows:
  branch:
    jobs:
      - build-push-branch:
          context: org-global

  tag:
    jobs:
      - build-push-tag:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

  send-jokes:
    triggers:
      - schedule:
          cron: "22 01 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - send-jokes:
          context: org-global
